package edu.mit.csail.db.ml

import java.io.OutputStream

import org.apache.spark.sql.DataFrame

/**
 * Abstract class for models. This represents the actual model generated by the
 * system that can is fit on some data and can be used to predict
 * Created by mvartak on 10/11/15.
 */
abstract class Model {
  /**
   * Predict target variables using this model.
   * By default, the output data frame should contain an output column called "prediction".
   * This should be overridden in subclasses and configurable by the user.
   * @param data
   * @return
   */
  def predict(data: DataFrame): DataFrame

  /**
   * Export model to a different format
   * @param format
   * @param out
   */
  def export(format: String, out:OutputStream)
}